
import java.awt.Component;
import java.awt.Desktop;
import java.awt.EventQueue;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author John Calderaio
 */
public class NewJDialog extends javax.swing.JDialog {

    public String language1String;
    public String language2String;
    public TranslateService ts = new TranslateService();
    public Language lang = new Language();
    public HashMap<String, String> lMap = new HashMap();
    private Component frame;

    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        textbox1.setText("");
        textbox2.setText("");
        lMap.put("Afrikaans", "af");
        lMap.put("Albanian", "sq");
        lMap.put("Arabic", "ar");
        lMap.put("Azerbaijani", "az");
        lMap.put("Basque", "eu");
        lMap.put("Bengali", "bn");
        lMap.put("Belarusian", "be");
        lMap.put("Bulgarian", "bg");
        lMap.put("Catalan", "ca");
        lMap.put("ChineseSimplified", "zh-CN");
        lMap.put("ChineseTraditional", "zh-TW");
        lMap.put("Croatian", "hr");
        lMap.put("Czech", "cs");
        lMap.put("Danish", "da");
        lMap.put("Dutch", "nl");
        lMap.put("English", "en");
        lMap.put("Esperanto", "eo");
        lMap.put("Estonian", "et");
        lMap.put("Filipino", "tl");
        lMap.put("Finnish", "fi");
        lMap.put("French", "fr");
        lMap.put("Galician", "gl");
        lMap.put("Georgian", "ka");
        lMap.put("German", "de");
        lMap.put("Greek", "el");
        lMap.put("Gujarati", "gu");
        lMap.put("HaitianCreole", "ht");
        lMap.put("Hebrew", "iw");
        lMap.put("Hindi", "hi");
        lMap.put("Hungarian", "hu");
        lMap.put("Icelandic", "is");
        lMap.put("Indonesian", "id");
        lMap.put("Irish", "ga");
        lMap.put("Italian", "it");
        lMap.put("Japanese", "ja");
        lMap.put("Kannada", "kn");
        lMap.put("Korean", "ko");
        lMap.put("Latin", "la");
        lMap.put("Latvian", "lv");
        lMap.put("Lithuanian", "lt");
        lMap.put("Macedonian", "mk");
        lMap.put("Malay", "ms");
        lMap.put("Maltese", "mt");
        lMap.put("Norwegian", "no");
        lMap.put("Persian", "fa");
        lMap.put("Polish", "pl");
        lMap.put("Portuguese", "pt");
        lMap.put("Romanian", "ro");
        lMap.put("Russian", "ru");
        lMap.put("Serbian", "sr");
        lMap.put("Slovak", "sk");
        lMap.put("Slovenian", "sl");
        lMap.put("Spanish", "es");
        lMap.put("Swahili", "sw");
        lMap.put("Swedish", "sv");
        lMap.put("Tamil", "ta");
        lMap.put("Telugu", "te");
        lMap.put("Thai", "th");
        lMap.put("Turkish", "tr");
        lMap.put("Ukrainian", "uk");
        lMap.put("Urdu", "ur");
        lMap.put("Vietnamese", "vi");
        lMap.put("Welsh", "cy");
        lMap.put("Yiddish", "yi");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        menuBar2 = new java.awt.MenuBar();
        menu3 = new java.awt.Menu();
        menu4 = new java.awt.Menu();
        language1 = new javax.swing.JComboBox();
        language2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        button1 = new javax.swing.JButton();
        completeInteraction = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textbox2 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        translated1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        translated2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textbox1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        menu3.setLabel("File");
        menuBar2.add(menu3);

        menu4.setLabel("Edit");
        menuBar2.add(menu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        language1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Language", "Afrikaans", "Albanian", "Arabic", "Azerbaijani", "Basque", "Bengali", "Belarusian", "Bulgarian", "Catalan", "ChineseSimplified", "ChineseTraditional", "Croatian", "Czech", "Danish", "Dutch", "English", "Esperanto", "Estonian", "Filipino", "Finnish", "French", "Galician", "Georgian", "German", "Greek", "Gujarati", "HaitianCreole", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Irish", "Italian", "Japanese", "Kannada", "Korean", "Latin", "Latvian", "Lithuanian", "Macedonian", "Malay", "Maltese", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Slovak", "Slovenian", "Spanish", "Swahili", "Swedish", "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese", "Welsh", "Yiddish" }));
        language1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                language1ActionPerformed(evt);
            }
        });

        language2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Language", "Afrikaans", "Albanian", "Arabic", "Azerbaijani", "Basque", "Bengali", "Belarusian", "Bulgarian", "Catalan", "ChineseSimplified", "ChineseTraditional", "Croatian", "Czech", "Danish", "Dutch", "English", "Esperanto", "Estonian", "Filipino", "Finnish", "French", "Galician", "Georgian", "German", "Greek", "Gujarati", "HaitianCreole", "Hebrew", "Hindi", "Hungarian", "Icelandic", "Indonesian", "Irish", "Italian", "Japanese", "Kannada", "Korean", "Latin", "Latvian", "Lithuanian", "Macedonian", "Malay", "Maltese", "Norwegian", "Persian", "Polish", "Portuguese", "Romanian", "Russian", "Serbian", "Slovak", "Slovenian", "Spanish", "Swahili", "Swedish", "Tamil", "Telugu", "Thai", "Turkish", "Ukrainian", "Urdu", "Vietnamese", "Welsh", "Yiddish" }));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setText("Enter Text");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Enter Text");

        button1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        button1.setText("→");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        completeInteraction.setText("Complete Interaction");
        completeInteraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeInteractionActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        button2.setText("←");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        textbox2.setColumns(20);
        textbox2.setLineWrap(true);
        textbox2.setRows(5);
        jScrollPane5.setViewportView(textbox2);

        translated1.setColumns(20);
        translated1.setLineWrap(true);
        translated1.setRows(5);
        jScrollPane1.setViewportView(translated1);

        translated2.setColumns(20);
        translated2.setLineWrap(true);
        translated2.setRows(5);
        jScrollPane2.setViewportView(translated2);

        textbox1.setColumns(20);
        textbox1.setLineWrap(true);
        textbox1.setRows(5);
        jScrollPane3.setViewportView(textbox1);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("User 1");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel4.setText("User 2");

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(language1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(language2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(163, 163, 163)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(174, 174, 174)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(button2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(completeInteraction))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(language1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(language2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button1)
                            .addComponent(button2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clearButton)
                        .addGap(18, 18, 18)
                        .addComponent(completeInteraction))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed

        language1String = language1.getSelectedItem().toString();
        language2String = language2.getSelectedItem().toString();

        if (language1String.equals("Select Language") && language2String.equals("Select Language") && textbox1.getText().equals("")) {
            JOptionPane.showMessageDialog(frame,
                    "Please Input Text to Translate and Select Languages",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
        } else if (language1String.equals("Select Language") || language2String.equals("Select Language")) {
            JOptionPane.showMessageDialog(frame,
                    "Please Select a Language",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
            textbox1.setText("");
            textbox2.setText("");
        } else if (textbox1.getText().equals("")) {
            JOptionPane.showMessageDialog(frame,
                    "Please Input Text to Translate",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
        } else if (language1String.equals(language2String)) {
            JOptionPane.showMessageDialog(frame,
                    "Languages are the Same! Select a different Language",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
        } else {

            EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                        translated1.append("\nMe: " + textbox1.getText());
                        translated2.append("\nThem: " + ts.translate(textbox1.getText(), lMap.get(language2String), lMap.get(language1String)));
                        textbox1.setText("");
                        textbox2.setText("");
                    } catch (IOException ex) {
                        Logger.getLogger(NewJDialog.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });

        }

    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed

        language1String = language1.getSelectedItem().toString();
        language2String = language2.getSelectedItem().toString();

        if (language1String.equals("Select Language") && language2String.equals("Select Language") && textbox2.getText().equals("")) {
            JOptionPane.showMessageDialog(frame,
                    "Please Input Text to Translate and Select Languages",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
        } else if (language1String.equals("Select Language") || language2String.equals("Select Language")) {
            JOptionPane.showMessageDialog(frame,
                    "Please Select a Language",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
            textbox1.setText("");
            textbox2.setText("");
        } else if (textbox2.getText().equals("")) {
            JOptionPane.showMessageDialog(frame,
                    "Please Input Text to Translate",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
        } else if (language2String.equals(language1String)) {
            JOptionPane.showMessageDialog(frame,
                    "Languages are the Same! Select a different Language",
                    "Inane warning",
                    JOptionPane.WARNING_MESSAGE);
        } else {

            EventQueue.invokeLater(new Runnable() {
                @Override
                public void run() {
                    try {
                        translated2.append("\nMe: " + textbox2.getText());
                        translated1.append("\nThem: " + ts.translate(textbox2.getText(), lMap.get(language1String), lMap.get(language2String)));
                        textbox2.setText("");
                        textbox1.setText("");
                    } catch (IOException ex) {
                        Logger.getLogger(NewJDialog.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });

        }

    }//GEN-LAST:event_button2ActionPerformed

    private void language1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_language1ActionPerformed

    }//GEN-LAST:event_language1ActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        translated1.setText("");
        translated2.setText("");
        textbox1.setText("");
        textbox2.setText("");
        language1.setSelectedIndex(0);
        language2.setSelectedIndex(0);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void completeInteractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeInteractionActionPerformed

        try {
            Desktop.getDesktop().browse(new URL("https://ufl.qualtrics.com/jfe/form/SV_bHjcqGsI3grvuGF").toURI());
        } catch (URISyntaxException | IOException e) {
        }


    }//GEN-LAST:event_completeInteractionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton completeInteraction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JComboBox language1;
    private javax.swing.JComboBox language2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.Menu menu3;
    private java.awt.Menu menu4;
    private java.awt.MenuBar menuBar1;
    private java.awt.MenuBar menuBar2;
    private javax.swing.JTextArea textbox1;
    private javax.swing.JTextArea textbox2;
    private javax.swing.JTextArea translated1;
    private javax.swing.JTextArea translated2;
    // End of variables declaration//GEN-END:variables
}
